version: '3'

services:
    mysql:
        image: mysql
        build: ./mysql
        container_name: mysql
        restart: always
        expose:
            - '3306'
        networks:
            - matcha_network
        env_file:
            - .env

    back:
        image: back
        build: ./back
        container_name: back
        restart: always
        networks:
            - matcha_network
        ports:
            - '8000:8000'
        volumes:
            - back:/app
        env_file:
            - .env
        depends_on:
            - mysql
            - redis
            - elasticsearch
    front:
        image: front
        build: ./front
        container_name: front
        ports:
            - '3000:3000'
        networks:
            - matcha_network
        volumes:
            - front:/app 

    redis:
        image: redis
        build: ./redis
        container_name: redis
        restart: always
        networks:
            - matcha_network
        expose:
            - '6379'
        env_file:
            - .env

    elasticsearch:
        image: elasticsearch
        build: ./elasticsearch
        container_name: elasticsearch
        restart: always
        networks:
            - matcha_network
        ports:
            - '9200:9200'
        environment:
            - discovery.type=single-node
            - ES_NETWORK_BIND_HOST="back:8000"
            - xpack.security.enabled=false
        env_file:
            - .env

volumes:
    back:
        name: back
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/jihkang/Desktop/ft_matcha/back
    front:
        name: front
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/jihkang/Desktop/ft_matcha/front


networks:
    matcha_network:
        driver: bridge

   

    # certs:
    #     name: certs
    #     driver: local
    #     driver_opts:
    #         type: none
    #         o: bind
    #         device: ./certs
